// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Mongodb = require("mongodb");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function Make(Info) {
  return (function () {
      var collection = /* record */[/* contents */undefined];
      var setup = function () {
        return Mongodb.MongoClient.connect(Info[/* uri */0]).then((function (client) {
                      collection[0] = Js_primitive.some(client.db(Info[/* db */1]).collection("blocks"));
                      return Promise.resolve(/* () */0);
                    }));
      };
      var count = function () {
        var match = collection[0];
        if (match !== undefined) {
          return Js_primitive.valFromOption(match).find().count();
        } else {
          return Promise.resolve(0);
        }
      };
      var save = function (block) {
        var match = collection[0];
        if (match !== undefined) {
          ((block._id = block.block_num));
          return Js_primitive.valFromOption(match).save(block).then((function () {
                        return Promise.resolve(true);
                      }));
        } else {
          return Promise.resolve(false);
        }
      };
      var largestBlockNum = function () {
        var match = collection[0];
        if (match !== undefined) {
          return Js_primitive.valFromOption(match).find().sort("block_num", -1).next().then((function (block) {
                        if (block == null) {
                          return Promise.resolve(0);
                        } else {
                          return Promise.resolve(Json_decode.field("block_num", Json_decode.$$int, block));
                        }
                      }));
        } else {
          return Promise.resolve(0);
        }
      };
      var findMissing = function () {
        return Promise.resolve(/* () */0);
      };
      return /* module */[
              /* setup */setup,
              /* count */count,
              /* save */save,
              /* largestBlockNum */largestBlockNum,
              /* findMissing */findMissing
            ];
    });
}

exports.Make = Make;
/* mongodb Not a pure module */
