// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Npmlog = require("npmlog");
var Database = require("./Database.js");
var SyncLoop = require("./SyncLoop.js");

var logo = "\n\n   ███████╗ ██████╗ ███████╗    ███████╗██╗   ██╗███╗   ██╗ ██████╗\n   ██╔════╝██╔═══██╗██╔════╝    ██╔════╝╚██╗ ██╔╝████╗  ██║██╔════╝\n   █████╗  ██║   ██║███████╗    ███████╗ ╚████╔╝ ██╔██╗ ██║██║\n   ██╔══╝  ██║   ██║╚════██║    ╚════██║  ╚██╔╝  ██║╚██╗██║██║\n   ███████╗╚██████╔╝███████║    ███████║   ██║   ██║ ╚████║╚██████╗\n   ╚══════╝ ╚═════╝ ╚══════╝    ╚══════╝   ╚═╝   ╚═╝  ╚═══╝ ╚═════╝\n\n";

function start() {
  return Database.setup(/* () */0).then((function () {
                    return SyncLoop.start(SyncLoop.initialState);
                  })).then((function () {
                  return Promise.resolve(/* () */0);
                })).catch((function (error) {
                return Promise.resolve((Npmlog.error("Start", "error", error), /* () */0));
              }));
}

Npmlog.info("Start", logo, "");

start(/* () */0);

exports.logo = logo;
exports.start = start;
/*  Not a pure module */
