version: '3'

services:

  arango:
    image: arangodb/arangodb:latest
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=openSesame

  mongo:
    image: mongo
    command: --smallfiles
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    ports:
      - 6379:6379
