// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Npmlog = require("npmlog");

setInterval((function () {
        Npmlog.info("AnalyzeBlocks", "Analyzing", "");
        return /* () */0;
      }), 5000);

/*  Not a pure module */
