// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';


var endpoints = /* array */[
  "http://104.156.59.166:8888",
  "http://149.202.180.100",
  "http://api.bitmars.one",
  "http://api.bp.antpool.com",
  "http://api.eosargentina.io",
  "http://api.eosgeneva.io",
  "http://api.eosmedi.com",
  "http://api.eosn.io",
  "http://api.eosnewyork.io",
  "http://api.eossocal.io",
  "http://api.eossweden.eu",
  "http://api.eossweden.se",
  "http://api.eostitan.com",
  "http://api.eosuk.io",
  "http://api.main.alohaeos.com",
  "http://api.proxy1a.sheos.org",
  "http://api.tokenika.io",
  "http://api1.eosasia.one",
  "http://api1.eostheworld.io:4865",
  "http://api2.eosgeneva.io",
  "http://blockgenesys.com:8888",
  "http://bp.blockchainlab.me:9090",
  "http://eos-api.privex.io",
  "http://eos-bp.bitfinex.com:8888",
  "http://eos.greymass.com",
  "http://eosbp-0.atticlab.net",
  "http://eu.eosdac.io",
  "http://fn001.eossv.org:80",
  "http://mainnet.bpnode.com:8888",
  "http://mainnet.eosarabia.org:2052",
  "http://mainnet.eoscalgary.io",
  "http://mainnet.eoscanada.com",
  "http://mainnet.libertyblock.io:8888",
  "http://node.eosflare.io",
  "http://node.eosvenezuela.io:8888",
  "http://node1.bp2.io",
  "http://node1.eosamericas.com:8888",
  "http://node1.eosvibes.io",
  "http://nodes.eos42.io",
  "http://peer2.eosthu.com:8082"
];

var dbUser = "root";

var dbPass = "openSesame";

var dbName = "eos";

var throttleTime = 1500;

var maxBlocksPerCycle = 5000;

var chainId = "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906";

exports.dbUser = dbUser;
exports.dbPass = dbPass;
exports.dbName = dbName;
exports.throttleTime = throttleTime;
exports.maxBlocksPerCycle = maxBlocksPerCycle;
exports.chainId = chainId;
exports.endpoints = endpoints;
/* No side effect */
