// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Eosr_Node = require("./Eosr_Node.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function Make() {
  return (function () {
      var startTime = new Date();
      var nodes = { };
      var chains = { };
      var addNode = function (node) {
        var key = Eosr_Node.key(node);
        nodes[key] = node;
        return /* () */0;
      };
      var addEndpoint = function (endpoint) {
        return addNode(Eosr_Node.make(endpoint));
      };
      var useNode = Eosr_Node.getInfo;
      var run = function () {
        return Promise.all(Belt_Array.map(Js_dict.values(nodes), useNode));
      };
      return /* module */[
              /* startTime */startTime,
              /* nodes */nodes,
              /* chains */chains,
              /* addNode */addNode,
              /* addEndpoint */addEndpoint,
              /* run */run
            ];
    });
}

exports.Make = Make;
/* Js_dict Not a pure module */
