// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Eosr_Bot = require("./Eosr_Bot.js");
var Eosr_Env = require("./Eosr_Env.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Eosr_Queue_Redis = require("./Queue/Eosr_Queue_Redis.js");
var Eosr_Store_Arango = require("./Store/Eosr_Store_Arango.js");

var Queue = Eosr_Queue_Redis.Make(/* module */[]);

var Store = Eosr_Store_Arango.Make(/* module */[
      /* db */"eos",
      /* user */"root",
      /* pass */"openSesame"
    ]);

var Bot = Eosr_Bot.Make(Queue)(Store);

Belt_Array.map(Eosr_Env.endpoints, Bot[/* addEndpoint */4]);

Curry._1(Bot[/* run */5], /* () */0).then((function (nodes) {
        return Promise.resolve((console.log("nodes", nodes), /* () */0));
      }));

exports.Queue = Queue;
exports.Store = Store;
exports.Bot = Bot;
/* Queue Not a pure module */
